/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: G1ngerBoy (https://sketchfab.com/G1ngerBoy)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/leather-and-fabric-sofa-c715fad78e6c4fc79b3b54d40ab50d07
title: Leather and Fabric Sofa
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Sillon({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={2}>
            <mesh
              geometry={nodes.Cube__0.geometry}
              material={materials["Scene_-_Root"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
